name: Code Quality

on: [push]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
      run: |
        pipenv install --dev
      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
      - name: Analysing the code with pylint
        run: |
          pylint `ls -R|grep .py$|xargs`
